### ISSUE TITLE
Is that possible to support filters in this chart?

### ISSUE THREAD

**Issue by tianchao-haohan** [mstoyano/kbn_c3js_vis#1]
As titled.
It will be better if the chart support filters in X-Axis.

**Comment by mstoyano** [comment]
Hello there, 

I'm sorry but right now I'm not able to add the filters feature (for the moment). Of course, you are right and filters in X-Axis is a great feature. Unfortunately i think C3JS doesn't support that feature(zoom feature instead), but anyways i will try to figure out something. 

For now you can filter data using the right upper corner or if you have a dashboard use x-axis filters on default kibana representation and effect will be seen in C3 charts automatically.

Thank you
