### ISSUE TITLE
Dual axis support

### ISSUE THREAD

**Issue by Prazzy** [mstoyano/kbn_c3js_vis#2]
There is a C3JS plugin already and it supports dual axis.

https://github.com/sbeyn/kibana-plugin-line-sg

I think we need to maintain a single plugin for C3JS.

**Comment by mstoyano** [comment]
Hello, 

this plugin is being developed by me and I have nothing to do with other plugins. I can't see the problem of having 2 plugins that uses the same JS library, we may have different approaches (each developer). You must take the decision of which will be more useful. 

But anyway, I will try to add that feature soon. Thanks for your comment.

**Comment by Prazzy** [comment]
Oh got it. I will compare both and contribute to your plugin for missing features..

**Comment by mstoyano** [comment]
That would be great. I appreciate it alot.
